name: twit-sentiment-group-2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - sentencepiece
  - tiktoken
  - pip:
      - apache-airflow==2.10.5       # cài bằng pip
      - mlflow>=2.10.0
      - torch>=2.2.0
      - torchvision
      - transformers>=4.37.0
      - accelerate>=0.25.0
      - numpy==1.26.4
      - pandas==2.1.4
      - scikit-learn>=1.4.0
      - azure-storage-blob>=12.19.0
      - azure-identity>=1.15.0
      - psycopg2-binary==2.9.10
      - python-dotenv==1.1.0
      - typing-extensions
      - matplotlib>=3.8.0
      - seaborn>=0.13.0
      - tqdm>=4.66.0
      - fastapi>=0.109.0
      - uvicorn>=0.27.0
      - pydantic==2.11.2
      - python-multipart>=0.0.7
      - requests==2.32.3
      - aiohttp==3.11.11
      - twikit==2.3.3
